import re
import shutil
from datetime import datetime
from pathlib import Path

from csxhair import Crosshair

CROSSHAIRS_CFG = "crosshairs.cfg"
AUTOEXEC_CFG = "autoexec.cfg"

_CVAR_ORDER = [
    "cl_crosshairstyle",
    "cl_crosshaircolor",
    "cl_crosshairsize",
    "cl_crosshairgap",
    "cl_crosshairalpha",
    "cl_crosshairusealpha",
    "cl_crosshairthickness",
    "cl_crosshaircolor_r",
    "cl_crosshaircolor_g",
    "cl_crosshaircolor_b",
    "cl_crosshair_drawoutline",
    "cl_crosshair_friendly_warning",
    "cl_crosshair_dynamic_maxdist_splitratio",
    "cl_crosshair_dynamic_splitalpha_innermod",
    "cl_crosshair_dynamic_splitalpha_outermod",
    "cl_crosshair_dynamic_splitdist",
    "cl_crosshair_outlinethickness",
    "cl_crosshair_recoil",
    "cl_crosshair_sniper_width",
    "cl_crosshairdot",
    "cl_crosshair_t",
    "cl_crosshairgap_useweaponvalue",
    "hud_showtargetid",
]

_BIND_RE = re.compile(r"^[A-Za-z0-9_+\\-]+$")
_CVAR_RE = re.compile(r"^(cl_crosshair[A-Za-z0-9_]*|hud_showtargetid)$")
_SHARE_CODE_RE = re.compile(r"^CSGO-[A-Za-z0-9]{5}(?:-[A-Za-z0-9]{5}){4}$")


def _clean_echo(text):
    return str(text).replace(chr(34), chr(39)).replace(";", ":").replace("\r", " ").replace("\n", " ").strip()


def _clean_bind(bind):
    bind = str(bind).strip()
    if not bind:
        return ""
    if not _BIND_RE.fullmatch(bind):
        raise ValueError("Cycle bind can only contain letters, numbers, underscore, plus, or dash.")
    return bind.lower()


def _clean_share_code(code):
    code = str(code).strip()
    if not code:
        return ""
    if not _SHARE_CODE_RE.fullmatch(code):
        raise ValueError(f"Invalid crosshair share code: {code!r}")
    return code


def _format_value(value):
    if isinstance(value, bool):
        return str(int(value))
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return (f"{value:.6f}".rstrip("0").rstrip(".")) or "0"
    text = str(value).strip()
    if not re.fullmatch(r"-?\d+(\.\d+)?", text):
        raise ValueError(f"Unsafe cvar value: {text!r}")
    return text


def _ordered_cvars(cvars):
    ordered = [cvar for cvar in _CVAR_ORDER if cvar in cvars]
    extras = sorted(cvar for cvar in cvars if cvar not in _CVAR_ORDER and _CVAR_RE.fullmatch(cvar))
    return ordered + extras


def _cvar_lines(cvars, echo=None):
    lines = []
    if echo:
        lines.append(f"echo {_clean_echo(echo)}")
    for cvar in _ordered_cvars(cvars):
        lines.append(f"{cvar} {_format_value(cvars[cvar])}")
    return lines


def _cvar_string(cvars, echo=None):
    return "; ".join(_cvar_lines(cvars, echo=echo))


def _share_code_string(share_code):
    share_code = _clean_share_code(share_code)
    return f"cl_crosshair_sharecode {share_code}" if share_code else ""


def _parse_decoded_command(line):
    parts = line.split()
    if len(parts) < 2 or not _CVAR_RE.fullmatch(parts[0]):
        return None
    raw = parts[1].strip(chr(34))
    if raw.lower() in {"true", "false"}:
        value = 1 if raw.lower() == "true" else 0
    else:
        try:
            value = int(raw)
        except ValueError:
            value = float(raw)
    return parts[0], value


def _decode_share_code_cvars(share_code):
    cvars = {}
    for command in Crosshair.decode(_clean_share_code(share_code)).cs2_commands:
        parsed = _parse_decoded_command(command)
        if parsed:
            cvar, value = parsed
            cvars[cvar] = value
    return cvars


def _cvars_for_data(data):
    cvars = data.get("cvars", {})
    if cvars:
        return cvars
    share_code = data.get("share_code", "")
    if share_code:
        return _decode_share_code_cvars(share_code)
    return {}


def command_string(cvars=None, share_code=""):
    if cvars:
        return _cvar_string(cvars)
    if share_code:
        return _share_code_string(share_code)
    return ""


def _preset_filename(letter):
    return f"cross{letter}.cfg"


def _preset_lines(letter, data):
    label = data.get("label", letter.upper())
    return [
        "// ================================================",
        f"// Crosshair {letter.upper()} - {_clean_echo(label)}",
        "// generated by CS2 Crosshair Manager",
        "// ================================================",
        "",
        *_cvar_lines(_cvars_for_data(data), echo=f"[Crosshair {letter.upper()} - {label}]"),
        "",
    ]


def _make_alias(letter, cycle_next=None, target_letter=None):
    target_letter = target_letter or letter
    body = f"exec cross{target_letter}"
    if cycle_next:
        body += f"; alias crosscycle cross{cycle_next}_c"
    return f"alias cross{letter} {chr(34)}{body}{chr(34)}"


def _make_reset_block():
    lines = ["// ----- reset stale aliases -----"]
    lines.append('alias crosscycle ""')
    lines.append('alias crossg_toggle ""')
    for letter in "abcdefghijklmnopqrstuvwxyz":
        lines.append(f'alias cross{letter} ""')
        lines.append(f'alias cross{letter.upper()} ""')
        lines.append(f'alias cross{letter}_c ""')
        lines.append(f'alias cross{letter.upper()}_c ""')
        lines.append(f'alias crossg{letter} ""')
        lines.append(f'alias crossg{letter.upper()} ""')
    return lines


def _cycle_letters(config):
    crosshairs = config.get("crosshairs", {})
    selected = [letter for letter in config.get("cycle_letters", []) if letter in crosshairs]
    if not selected:
        selected = sorted(crosshairs.keys())
    return [letter for letter in selected if len(letter) == 1 and letter in "abcdefghijklmnopqrstuvwxyz"]


def _make_cycle_block(config):
    letters = _cycle_letters(config)
    bind = _clean_bind(config.get("cycle_bind", ""))
    if len(letters) < 2 or not bind:
        return ""
    lines = ["", "// ----- cycle bind -----", f"alias crosscycle {chr(34)}cross{letters[0]}_c{chr(34)}"]
    for index, letter in enumerate(letters):
        next_letter = letters[(index + 1) % len(letters)]
        lines.append(_make_alias(f"{letter}_c", cycle_next=next_letter, target_letter=letter))
    lines.append(f"bind {chr(34)}{bind}{chr(34)} {chr(34)}crosscycle{chr(34)}")
    return "\n".join(lines)


def write(config):
    cfg_path = Path(config.get("cs2_cfg_path", ""))
    if not cfg_path.exists() or not cfg_path.is_dir():
        raise FileNotFoundError(f"CS2 cfg path not found: {cfg_path}")
    crosshairs = config.get("crosshairs", {})
    for letter, data in sorted(crosshairs.items()):
        if len(letter) != 1 or letter not in "abcdefghijklmnopqrstuvwxyz":
            continue
        (cfg_path / _preset_filename(letter)).write_text(chr(10).join(_preset_lines(letter, data)))

    lines = [
        "// ================================================",
        "// generated by CS2 Crosshair Manager",
        "// do not edit - changes will be overwritten",
        "// Note: aliases/cycle binds may not work in workshop maps",
        "// ================================================",
        "",
        *_make_reset_block(),
        "",
        "// ----- presets -----",
    ]
    for letter in sorted(crosshairs.keys()):
        if len(letter) != 1 or letter not in "abcdefghijklmnopqrstuvwxyz":
            continue
        lines.append(_make_alias(letter))
    cycle = _make_cycle_block(config)
    if cycle:
        lines.append(cycle)
    lines.append("")
    out_path = cfg_path / CROSSHAIRS_CFG
    out_path.write_text("\n".join(lines))
    _ensure_autoexec(cfg_path / AUTOEXEC_CFG)
    return str(out_path)


def _has_active_exec_crosshairs(content):
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        if stripped.lower() == "exec crosshairs":
            return True
    return False


def _ensure_autoexec(autoexec_path):
    exec_line = "exec crosshairs\n"
    if not autoexec_path.exists():
        autoexec_path.write_text(exec_line)
        return
    content = autoexec_path.read_text(errors="replace")
    if _has_active_exec_crosshairs(content):
        return
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = autoexec_path.with_name(f"{autoexec_path.name}.bak-{stamp}")
    shutil.copy2(autoexec_path, backup_path)
    with autoexec_path.open("a") as handle:
        if content and not content.endswith("\n"):
            handle.write("\n")
        handle.write(exec_line)
